/**
 * Seed catalog for listings — used only by scripts/seed-listings.ts.
 * Not imported by the Next.js app runtime.
 */
import { getAreaTier, type AreaTier } from '../../lib/areas'
import type { Property, PropertyImage } from '../../lib/properties'

function withTier(area: string): AreaTier {
  return getAreaTier(area) ?? 'mid'
}

/* -------------------------------------------------------------------------- */
/* Seed dataset only — not imported by the Next.js app runtime.                */
/* -------------------------------------------------------------------------- */

const IMG = {
  apt1: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=640&q=70',
  apt2: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=640&q=70',
  apt3: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=640&q=70',
  apt4: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=640&q=70',
  house1: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=640&q=70',
  house2: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=640&q=70',
  house3: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=640&q=70',
  mansion: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=640&q=70',
  office1: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=640&q=70',
  office2: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=640&q=70',
  retail: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=70',
  warehouse: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=640&q=70',
  land1: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=640&q=70',
  land2: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=640&q=70',
  land3: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=640&q=70',
  land4: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=640&q=70&sat=-20',
} as const

function img(url: string, alt: string): PropertyImage[] {
  // Cover + 4-tile + extras (9 photos) for gallery: hero → 2×2 → more
  const GALLERY_COUNT = 9
  const pool = Object.values(IMG)
  const extras = pool.filter((s) => s !== url)
  const urls = [url, ...extras].slice(0, GALLERY_COUNT)
  while (urls.length < GALLERY_COUNT) urls.push(url)
  const tags = [
    'Exterior',
    'Living area',
    'Kitchen',
    'Bedroom',
    'Bathroom',
    'Dining',
    'Compound',
    'View',
    'Detail',
  ]
  return urls.map((u, i) => ({
    url: u,
    alt: i === 0 ? alt : `${alt} — photo ${i + 1}`,
    isCover: i === 0,
    roomTag: tags[i],
  }))
}

const PROPERTIES: Property[] = [
  /* —— Mid-market residential rentals (popular rentals row) —— */
  {
    id: '1',
    slug: 'modern-2-bedroom-apartment-ntinda',
    title: 'Modern 2 Bedroom Apartment',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'apartment',
    area: 'Ntinda',
    areaTier: withTier('Ntinda'),
    city: 'Kampala',
    priceUgx: 1_800_000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 120,
    images: img(IMG.apt1, 'Modern 2 bedroom apartment for rent in Ntinda'),
    description: 'Apartment in Ntinda — 2 bedrooms, 2 bathrooms, 120 m².',
    listedAt: '2026-06-01',
    verified: true,
    isFeatured: true,
    views7d: 420,
    inquiries7d: 18,
  },
  {
    id: '2',
    slug: 'spacious-3-bedroom-house-kira',
    title: 'Spacious 3 Bedroom House',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'storeyed',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 1_200_000,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 160,
    images: img(IMG.house1, '3 bedroom storeyed house for rent in Kira'),
    description: 'Storeyed house in Kira — 3 bedrooms, 2 bathrooms, 160 m².',
    listedAt: '2026-06-03',
    verified: true,
    views7d: 310,
    inquiries7d: 12,
  },
  {
    id: '11',
    slug: 'bright-1-bedroom-apartment-najjera',
    title: 'Bright 1 Bedroom Apartment',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'apartment',
    area: 'Najjera',
    areaTier: withTier('Najjera'),
    city: 'Kampala',
    priceUgx: 900_000,
    bedrooms: 1,
    bathrooms: 1,
    sizeSqm: 65,
    images: img(IMG.apt3, '1 bedroom apartment for rent in Najjera'),
    description: 'Apartment in Najjera — 1 bedroom, 1 bathroom, 65 m².',
    listedAt: '2026-06-21',
    verified: true,
    isFeatured: true,
    views7d: 280,
    inquiries7d: 15,
  },
  {
    id: '12',
    slug: 'family-3-bedroom-townhouse-naalya',
    title: 'Family 3 Bedroom Townhouse',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'townhouse',
    area: 'Naalya',
    areaTier: withTier('Naalya'),
    city: 'Kampala',
    priceUgx: 2_100_000,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqm: 180,
    images: img(IMG.house3, '3 bedroom townhouse for rent in Naalya'),
    description: 'Townhouse in Naalya — 3 bedrooms, 3 bathrooms, 180 m².',
    listedAt: '2026-06-22',
    verified: true,
    views7d: 265,
    inquiries7d: 11,
  },
  {
    id: '13',
    slug: 'cozy-studio-bukoto',
    title: 'Cozy Studio Flat',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'studio',
    area: 'Bukoto',
    areaTier: withTier('Bukoto'),
    city: 'Kampala',
    priceUgx: 750_000,
    bedrooms: 0,
    bathrooms: 1,
    sizeSqm: 42,
    images: img(IMG.apt4, 'Studio flat for rent in Bukoto'),
    description: 'Studio in Bukoto — compact 42 m² with fitted kitchen.',
    listedAt: '2026-06-23',
    verified: true,
    views7d: 340,
    inquiries7d: 20,
  },
  {
    id: '14',
    slug: 'self-contained-2bed-ntinda',
    title: 'Self-contained 2 Bedroom',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'selfcontained',
    area: 'Ntinda',
    areaTier: withTier('Ntinda'),
    city: 'Kampala',
    priceUgx: 1_400_000,
    bedrooms: 2,
    bathrooms: 1,
    sizeSqm: 95,
    images: img(IMG.apt2, 'Self-contained 2 bedroom for rent in Ntinda'),
    description: 'Self-contained unit in Ntinda — 2 bedrooms, 95 m².',
    listedAt: '2026-06-24',
    verified: true,
    isFeatured: true,
    views7d: 390,
    inquiries7d: 16,
  },
  {
    id: '15',
    slug: '4-bedroom-bungalow-kira-rent',
    title: '4 Bedroom Bungalow',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'bungalow',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 2_800_000,
    bedrooms: 4,
    bathrooms: 3,
    sizeSqm: 240,
    images: img(IMG.house2, '4 bedroom bungalow for rent in Kira'),
    description: 'Bungalow in Kira — 4 bedrooms, 3 bathrooms, 240 m².',
    listedAt: '2026-06-25',
    verified: true,
    views7d: 210,
    inquiries7d: 9,
  },
  {
    id: '16',
    slug: '2-bedroom-maisonette-najjera',
    title: '2 Bedroom Maisonette',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'maisonette',
    area: 'Najjera',
    areaTier: withTier('Najjera'),
    city: 'Kampala',
    priceUgx: 1_550_000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 110,
    images: img(IMG.apt1, '2 bedroom maisonette for rent in Najjera'),
    description: 'Maisonette in Najjera — 2 bedrooms, 2 bathrooms, 110 m².',
    listedAt: '2026-06-26',
    verified: true,
    views7d: 255,
    inquiries7d: 13,
  },
  {
    id: '17',
    slug: '3-bedroom-apartment-naalya',
    title: '3 Bedroom Apartment',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'apartment',
    area: 'Naalya',
    areaTier: withTier('Naalya'),
    city: 'Kampala',
    priceUgx: 1_950_000,
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 145,
    images: img(IMG.apt3, '3 bedroom apartment for rent in Naalya'),
    description: 'Apartment in Naalya — 3 bedrooms, 2 bathrooms, 145 m².',
    listedAt: '2026-06-27',
    verified: true,
    isFeatured: true,
    views7d: 300,
    inquiries7d: 14,
  },
  {
    id: '18',
    slug: 'bedsitter-bukoto',
    title: 'Furnished Bedsitter',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'bedsitter',
    area: 'Bukoto',
    areaTier: withTier('Bukoto'),
    city: 'Kampala',
    priceUgx: 550_000,
    bedrooms: 0,
    bathrooms: 1,
    sizeSqm: 28,
    images: img(IMG.apt4, 'Bedsitter for rent in Bukoto'),
    description: 'Bedsitter in Bukoto — furnished, 28 m².',
    listedAt: '2026-06-28',
    verified: true,
    views7d: 445,
    inquiries7d: 28,
  },

  /* —— Prime / other residential —— */
  {
    id: '4',
    slug: 'furnished-2-bedroom-apartment-kololo',
    title: 'Furnished 2 Bedroom Apartment',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'apartment',
    area: 'Kololo',
    areaTier: withTier('Kololo'),
    city: 'Kampala',
    priceUgx: 4_500_000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 130,
    images: img(IMG.apt2, 'Furnished 2 bedroom apartment for rent in Kololo'),
    description: 'Furnished apartment in Kololo — 2 bedrooms, 130 m².',
    listedAt: '2026-06-08',
    verified: true,
    isFeatured: true,
    views7d: 510,
    inquiries7d: 31,
  },
  {
    id: '5',
    slug: '4-bedroom-storeyed-house-kira-sale',
    title: '4 Bedroom Storeyed House',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'storeyed',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 380_000_000,
    bedrooms: 4,
    bathrooms: 4,
    sizeSqm: 300,
    titleStatus: 'freehold',
    images: img(IMG.house2, '4 bedroom storeyed house for sale in Kira'),
    description: 'Storeyed house in Kira — for sale. 4 bedrooms, 300 m².',
    listedAt: '2026-06-10',
    verified: true,
    isFeatured: true,
    views7d: 190,
    inquiries7d: 9,
  },
  {
    id: '6',
    slug: '5-bedroom-hilltop-mansion-muyenga',
    title: '5 Bedroom Hilltop Mansion',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'mansion',
    area: 'Muyenga',
    areaTier: withTier('Muyenga'),
    city: 'Kampala',
    priceUgx: 1_200_000_000,
    bedrooms: 5,
    bathrooms: 6,
    sizeSqm: 650,
    titleStatus: 'mailo',
    images: img(IMG.mansion, '5 bedroom mansion for sale in Muyenga'),
    description: 'Mansion in Muyenga — for sale. 5 bedrooms, 650 m².',
    priceNegotiable: true,
    listedAt: '2026-06-12',
    verified: true,
    isFeatured: true,
    views7d: 240,
    inquiries7d: 14,
  },
  {
    id: '19',
    slug: '3-bedroom-apartment-naguru-sale',
    title: '3 Bedroom Apartment — Naguru',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'apartment',
    area: 'Naguru',
    areaTier: withTier('Naguru'),
    city: 'Kampala',
    priceUgx: 620_000_000,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqm: 185,
    titleStatus: 'leasehold',
    images: img(IMG.apt3, '3 bedroom apartment for sale in Naguru'),
    description: 'Apartment in Naguru — for sale. 3 bedrooms, 185 m².',
    listedAt: '2026-06-29',
    verified: true,
    isFeatured: true,
    views7d: 175,
    inquiries7d: 8,
  },
  {
    id: '20',
    slug: 'townhouse-lubowa-sale',
    title: '4 Bedroom Townhouse — Lubowa',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'residential',
    kind: 'townhouse',
    area: 'Lubowa',
    areaTier: withTier('Lubowa'),
    city: 'Kampala',
    priceUgx: 780_000_000,
    bedrooms: 4,
    bathrooms: 4,
    sizeSqm: 320,
    titleStatus: 'freehold',
    images: img(IMG.house3, '4 bedroom townhouse for sale in Lubowa'),
    description: 'Townhouse in Lubowa — for sale. 4 bedrooms, 320 m².',
    listedAt: '2026-06-30',
    verified: true,
    isFeatured: true,
    views7d: 155,
    inquiries7d: 7,
  },

  /* —— Commercial (rent + sale) —— */
  {
    id: '3',
    slug: 'office-suite-nakasero',
    title: 'Open-plan Office Suite',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'office',
    area: 'Nakasero',
    areaTier: withTier('Nakasero'),
    city: 'Kampala',
    priceUgx: 8_500_000,
    sizeSqm: 220,
    images: img(IMG.office1, 'Office suite for rent in Nakasero'),
    description: 'Office in Nakasero — 220 m² open-plan floor.',
    listedAt: '2026-06-05',
    verified: true,
    isFeatured: true,
    views7d: 280,
    inquiries7d: 22,
  },
  {
    id: '7',
    slug: 'retail-unit-ntinda-sale',
    title: 'Ground-floor Retail Unit',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'retail',
    area: 'Ntinda',
    areaTier: withTier('Ntinda'),
    city: 'Kampala',
    priceUgx: 520_000_000,
    sizeSqm: 95,
    titleStatus: 'leasehold',
    images: img(IMG.retail, 'Retail unit for sale in Ntinda'),
    description: 'Retail unit in Ntinda — for sale. 95 m² street-facing.',
    listedAt: '2026-06-14',
    verified: true,
    views7d: 160,
    inquiries7d: 7,
  },
  {
    id: '21',
    slug: 'warehouse-kira-rent',
    title: 'Warehouse with Yard',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'industrial',
    kind: 'warehouse',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 6_200_000,
    sizeSqm: 800,
    images: img(IMG.warehouse, 'Warehouse for rent in Kira'),
    description: 'Warehouse in Kira — 800 m² with loading yard.',
    listedAt: '2026-07-01',
    verified: true,
    views7d: 140,
    inquiries7d: 10,
  },
  {
    id: '22',
    slug: 'retail-shop-bugolobi-rent',
    title: 'Street-front Shop',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'retail',
    area: 'Bugolobi',
    areaTier: withTier('Bugolobi'),
    city: 'Kampala',
    priceUgx: 3_800_000,
    sizeSqm: 70,
    images: img(IMG.retail, 'Retail shop for rent in Bugolobi'),
    description: 'Retail in Bugolobi — 70 m² high-traffic frontage.',
    listedAt: '2026-07-02',
    verified: true,
    isFeatured: true,
    views7d: 220,
    inquiries7d: 12,
  },
  {
    id: '23',
    slug: 'coworking-office-kololo-rent',
    title: 'Furnished Office Floor',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'office',
    area: 'Kololo',
    areaTier: withTier('Kololo'),
    city: 'Kampala',
    priceUgx: 12_000_000,
    sizeSqm: 180,
    images: img(IMG.office2, 'Furnished office for rent in Kololo'),
    description: 'Office in Kololo — furnished 180 m² floor.',
    listedAt: '2026-07-03',
    verified: true,
    views7d: 195,
    inquiries7d: 11,
  },
  {
    id: '24',
    slug: 'mixed-use-ntinda-sale',
    title: 'Mixed-use Building',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'mixed-use',
    kind: 'mixed-use-building',
    area: 'Ntinda',
    areaTier: withTier('Ntinda'),
    city: 'Kampala',
    priceUgx: 1_450_000_000,
    sizeSqm: 520,
    titleStatus: 'mailo',
    images: img(IMG.office1, 'Mixed-use building for sale in Ntinda'),
    description: 'Mixed-use in Ntinda — for sale. Shops + offices, 520 m².',
    listedAt: '2026-07-04',
    verified: true,
    views7d: 130,
    inquiries7d: 6,
  },
  {
    id: '25',
    slug: 'office-suite-nakasero-sale',
    title: 'Corner Office Suite',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'office',
    area: 'Nakasero',
    areaTier: withTier('Nakasero'),
    city: 'Kampala',
    priceUgx: 890_000_000,
    sizeSqm: 160,
    titleStatus: 'leasehold',
    images: img(IMG.office2, 'Office suite for sale in Nakasero'),
    description: 'Office in Nakasero — for sale. 160 m² corner suite.',
    listedAt: '2026-07-05',
    verified: true,
    views7d: 110,
    inquiries7d: 5,
  },
  {
    id: '26',
    slug: 'warehouse-wakiso-sale',
    title: 'Industrial Warehouse',
    listingMode: 'sale',
    status: 'published',
    category: 'property',
    useClass: 'industrial',
    kind: 'warehouse',
    area: 'Wakiso',
    areaTier: withTier('Wakiso'),
    city: 'Wakiso',
    priceUgx: 680_000_000,
    sizeSqm: 1_200,
    titleStatus: 'freehold',
    images: img(IMG.warehouse, 'Warehouse for sale in Wakiso'),
    description: 'Warehouse in Wakiso — for sale. 1,200 m² freehold.',
    listedAt: '2026-07-06',
    verified: true,
    views7d: 95,
    inquiries7d: 4,
  },
  {
    id: '27',
    slug: 'retail-mall-unit-naalya-rent',
    title: 'Mall Retail Unit',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'retail',
    area: 'Naalya',
    areaTier: withTier('Naalya'),
    city: 'Kampala',
    priceUgx: 4_500_000,
    sizeSqm: 55,
    images: img(IMG.retail, 'Mall retail unit for rent in Naalya'),
    description: 'Retail in Naalya mall — 55 m² fitted unit.',
    listedAt: '2026-07-07',
    verified: true,
    views7d: 170,
    inquiries7d: 8,
  },
  {
    id: '28',
    slug: 'serviced-office-bugolobi-rent',
    title: 'Serviced Office Pods',
    listingMode: 'rent',
    status: 'published',
    category: 'property',
    useClass: 'commercial',
    kind: 'office',
    area: 'Bugolobi',
    areaTier: withTier('Bugolobi'),
    city: 'Kampala',
    priceUgx: 5_500_000,
    sizeSqm: 90,
    images: img(IMG.office1, 'Serviced office for rent in Bugolobi'),
    description: 'Serviced offices in Bugolobi — 90 m², utilities included.',
    listedAt: '2026-07-08',
    verified: true,
    views7d: 185,
    inquiries7d: 9,
  },

  /* —— Land for sale —— */
  {
    id: '8',
    slug: 'residential-plot-kira-50x100',
    title: 'Residential Plot in Kira',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'residential',
    landKind: 'residential-plot',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 95_000_000,
    plotDimensions: '50 x 100 ft',
    titleStatus: 'freehold',
    images: img(IMG.land1, 'Residential plot 50x100 for sale in Kira'),
    description: 'Land in Kira — 50 x 100 ft, titled, ready to build.',
    listedAt: '2026-06-16',
    verified: true,
    isFeatured: true,
    views7d: 350,
    inquiries7d: 25,
  },
  {
    id: '9',
    slug: 'commercial-plot-ntinda-100x100',
    title: 'Commercial Corner Plot',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'commercial',
    landKind: 'commercial-plot',
    area: 'Ntinda',
    areaTier: withTier('Ntinda'),
    city: 'Kampala',
    priceUgx: 320_000_000,
    plotDimensions: '100 x 100 ft',
    titleStatus: 'mailo',
    images: img(IMG.land2, 'Commercial plot 100x100 for sale in Ntinda'),
    description: 'Land in Ntinda — corner 100 x 100 ft, commercial use.',
    listedAt: '2026-06-18',
    verified: true,
    views7d: 120,
    inquiries7d: 6,
  },
  {
    id: '10',
    slug: 'agricultural-land-mukono',
    title: 'Agricultural Acreage',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'agricultural',
    landKind: 'agricultural',
    area: 'Mukono',
    areaTier: withTier('Mukono'),
    city: 'Mukono',
    priceUgx: 180_000_000,
    plotDimensions: '2 acres',
    titleStatus: 'kibanja',
    images: img(IMG.land3, 'Agricultural land 2 acres for sale in Mukono'),
    description:
      'Agricultural land in Mukono — about 2 acres under kibanja tenure.',
    listedAt: '2026-06-20',
    verified: true,
    views7d: 90,
    inquiries7d: 4,
  },
  {
    id: '29',
    slug: 'residential-plot-najjera-50x100',
    title: 'Plot in Najjera',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'residential',
    landKind: 'residential-plot',
    area: 'Najjera',
    areaTier: withTier('Najjera'),
    city: 'Kampala',
    priceUgx: 78_000_000,
    plotDimensions: '50 x 100 ft',
    titleStatus: 'freehold',
    images: img(IMG.land4, 'Residential plot for sale in Najjera'),
    description: 'Land in Najjera — 50 x 100 ft freehold.',
    listedAt: '2026-07-09',
    verified: true,
    views7d: 200,
    inquiries7d: 11,
  },
  {
    id: '30',
    slug: 'residential-plot-gayaza-100x100',
    title: 'Large Plot — Gayaza',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'residential',
    landKind: 'residential-plot',
    area: 'Gayaza',
    areaTier: withTier('Gayaza'),
    city: 'Kampala',
    priceUgx: 65_000_000,
    plotDimensions: '100 x 100 ft',
    titleStatus: 'mailo',
    images: img(IMG.land1, 'Residential plot for sale in Gayaza'),
    description: 'Land in Gayaza — 100 x 100 ft mailo.',
    listedAt: '2026-07-10',
    verified: true,
    views7d: 180,
    inquiries7d: 10,
  },
  {
    id: '31',
    slug: 'commercial-plot-nakasero',
    title: 'Prime Commercial Plot — Nakasero',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'commercial',
    landKind: 'commercial-plot',
    area: 'Nakasero',
    areaTier: withTier('Nakasero'),
    city: 'Kampala',
    priceUgx: 2_100_000_000,
    plotDimensions: '0.25 acres',
    titleStatus: 'leasehold',
    images: img(IMG.land2, 'Commercial plot for sale in Nakasero'),
    description: 'Land in Nakasero — 0.25 acres, commercial leasehold.',
    listedAt: '2026-07-11',
    verified: true,
    isFeatured: true,
    views7d: 145,
    inquiries7d: 8,
  },
  {
    id: '32',
    slug: 'agricultural-wakiso-5acres',
    title: '5 Acres — Wakiso',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'agricultural',
    landKind: 'agricultural',
    area: 'Wakiso',
    areaTier: withTier('Wakiso'),
    city: 'Wakiso',
    priceUgx: 420_000_000,
    plotDimensions: '5 acres',
    titleStatus: 'customary',
    images: img(IMG.land3, 'Agricultural land 5 acres for sale in Wakiso'),
    description: 'Agricultural land in Wakiso — 5 acres customary.',
    listedAt: '2026-07-12',
    verified: true,
    views7d: 100,
    inquiries7d: 5,
  },
  {
    id: '33',
    slug: 'residential-plot-outer-kira',
    title: 'Plot — Outer Kira',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'residential',
    landKind: 'residential-plot',
    area: 'Outer Kira',
    areaTier: withTier('Outer Kira'),
    city: 'Kampala',
    priceUgx: 48_000_000,
    plotDimensions: '50 x 100 ft',
    titleStatus: 'freehold',
    images: img(IMG.land4, 'Residential plot for sale in Outer Kira'),
    description: 'Land in Outer Kira — 50 x 100 ft freehold.',
    listedAt: '2026-07-13',
    verified: true,
    views7d: 230,
    inquiries7d: 14,
  },
  {
    id: '34',
    slug: 'residential-plot-namugongo',
    title: 'Quiet Plot — Namugongo',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'residential',
    landKind: 'residential-plot',
    area: 'Namugongo',
    areaTier: withTier('Namugongo'),
    city: 'Kampala',
    priceUgx: 110_000_000,
    plotDimensions: '50 x 100 ft',
    titleStatus: 'freehold',
    images: img(IMG.land1, 'Residential plot for sale in Namugongo'),
    description: 'Land in Namugongo — 50 x 100 ft freehold.',
    listedAt: '2026-07-14',
    verified: true,
    views7d: 160,
    inquiries7d: 7,
  },
  {
    id: '35',
    slug: 'commercial-plot-kira-road',
    title: 'Roadside Commercial Plot — Kira',
    listingMode: 'sale',
    status: 'published',
    category: 'land',
    useClass: 'commercial',
    landKind: 'commercial-plot',
    area: 'Kira',
    areaTier: withTier('Kira'),
    city: 'Kampala',
    priceUgx: 280_000_000,
    plotDimensions: '80 x 100 ft',
    titleStatus: 'mailo',
    images: img(IMG.land2, 'Commercial roadside plot for sale in Kira'),
    description: 'Land in Kira — 80 x 100 ft roadside commercial.',
    listedAt: '2026-07-15',
    verified: true,
    views7d: 135,
    inquiries7d: 6,
  },
]



export function getSeedProperties(): Property[] {
  return PROPERTIES.map((p) => p)
}
